#!/usr/bin/env bash

set -ueo pipefail
IFS=$'\n\t'

# Retries a command a with backoff.
#
# The retry count is given by ATTEMPTS (default 7), the
# initial backoff timeout is given by TIMEOUT in seconds
# (default 1/8 of a second.)
#
# Successive backoffs double the timeout.
#
# Beware of set -e killing your whole script!
function main {
  local max_attempts=${ATTEMPTS:-'7'}
  local timeout=${TIMEOUT:-0.125}
  local attempt=0
  local exitCode=0

  while (( attempt < max_attempts ))
  do
    set +e
    eval "$@"
    exitCode=$?
    set -e

    if [[ ${exitCode} == 0 ]]
    then
      break
    fi

    echo "Failure! Retrying in $timeout seconds.." 1>&2
    sleep "${timeout}"
    attempt=$(( attempt + 1 ))
    timeout=$(echo "${timeout}"*2 | bc)
  done

  if [[ ${exitCode} != 0 ]]
  then
    local IFS=" "
    echo "Failed $attempt times, abandoning ($*)" 1>&2
  fi

  return ${exitCode}
}

main "$@"
