version: '3'

services:

  # Database
  db:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  # Database Schema migration
  schema:
    image: teviotia/flyway
    entrypoint: with_backoff
    command: >
      flyway
      -user=postgres
      -password=password
      -url=jdbc:postgresql://db/postgres
      migrate
    volumes:
      - "./db:/flyway/sql"
    depends_on:
      - db
